id: I470D7CCC
legacy_id: P010573
ocr_import_info:
  bdrc_scan_id: W4PD2021
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T21:56:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:18:05.832713+00:00'
last_modified: 2022-09-04 05:20:00.234175
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD2021
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4PD2021
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཤེས་རབ་འོད་ཟེར།
  author: འཕྲེང་པོ་གཏེར་སྟོན་ཤེས་རབ་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9131998984356213
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4PD2030:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2030
      total_pages: 698
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4PD2030.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8632735730547835
    legacy_id: v008
  I4PD2026:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2026
      total_pages: 694
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD2026.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9158092418387556
    legacy_id: v004
  I4PD2025:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2025
      total_pages: 604
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD2025.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.917837553232697
    legacy_id: v003
  I4PD2028:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2028
      total_pages: 586
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4PD2028.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8876555068161789
    legacy_id: v006
  I4PD2029:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2029
      total_pages: 718
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4PD2029.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9063252725521108
    legacy_id: v007
  I4PD2023:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2023
      total_pages: 672
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD2023.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9283309166151807
    legacy_id: v001
  I4PD2027:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2027
      total_pages: 762
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD2027.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9373690341867854
    legacy_id: v005
  I4PD2024:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD2024
      total_pages: 868
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD2024.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9213503737104625
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
