id: I470D7CCC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:01:05+00:00'
last_modified: '2022-06-08T14:35:38.275305+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD2021
  title: གསུང་འབུམ། ཤེས་རབ་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2969':
      image_group_id: I4PD2023
      title: ''
      total_pages: 672
      order: 1
      base_file: 2969.txt
    1A49:
      image_group_id: I4PD2024
      title: ''
      total_pages: 868
      order: 2
      base_file: 1A49.txt
    838C:
      image_group_id: I4PD2025
      title: ''
      total_pages: 604
      order: 3
      base_file: 838C.txt
    C2A4:
      image_group_id: I4PD2026
      title: ''
      total_pages: 694
      order: 4
      base_file: C2A4.txt
    6CBF:
      image_group_id: I4PD2027
      title: ''
      total_pages: 762
      order: 5
      base_file: 6CBF.txt
    91A8:
      image_group_id: I4PD2028
      title: ''
      total_pages: 586
      order: 6
      base_file: 91A8.txt
    3A2D:
      image_group_id: I4PD2029
      title: ''
      total_pages: 718
      order: 7
      base_file: 3A2D.txt
    21F7:
      image_group_id: I4PD2030
      title: ''
      total_pages: 698
      order: 8
      base_file: 21F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
